/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewAD.Code;

import javax.swing.JFrame;

public class TAB5_ChiTietHD extends javax.swing.JFrame {

    private String maHD;

    public TAB5_ChiTietHD() {
        initComponents();
    }

    public TAB5_ChiTietHD(String maHD) {
        this.maHD = maHD;
        initComponents();
        System.out.println("Chi tiết hóa đơn cho mã: " + maHD); // kiểm tra log
        

    setResizable(false); //Không cho phóng to
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    setTitle("Chi tiết hóa đơn: " + maHD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new TAB5_ChiTietHD("HĐ123").setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
